### ISSUE TITLE
Supporting <Transforms> in signatures

### ISSUE THREAD

**Issue by jcassee** [yaronn/xml-crypto#100]
I have a signed XML document that uses XSL transformations before signing / verifying. This is the signature:

```
<?xml version="1.0" encoding="UTF-8"?>
<Envelope xmlns="urn:envelope">
	<Arbeidstijden xmlns="http://www.arbeidstijden.org" Id="idGegevenslevering">
		...
	</Arbeidstijden>
	<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
		<SignedInfo>
			<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></CanonicalizationMethod>
			<SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"></SignatureMethod>
			<Reference URI="#idGegevenslevering">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform>
					<Transform Algorithm="http://www.w3.org/TR/1999/REC-xslt-19991116">
						<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
							<xsl:output encoding="UTF-8" indent="no" method="xml" omit-xml-declaration="yes"
							            standalone="yes" version="1.0"></xsl:output>
							<xsl:template match="@*|*">
								<xsl:copy>
									<xsl:apply-templates select="@*|*"></xsl:apply-templates>
									<xsl:apply-templates select="text()"></xsl:apply-templates>
								</xsl:copy>
							</xsl:template>
							<xsl:template match="text()">
								<xsl:choose>
									<xsl:when test="../@codering = 'base64'">
										<xsl:value-of select="translate(normalize-space(.), ' ', '')"></xsl:value-of>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="normalize-space(.)"></xsl:value-of>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:template>
						</xsl:transform>
					</Transform>
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod>
				<DigestValue>...</DigestValue>
			</Reference>
			<Reference URI="#idKeyInfo">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform>
					<Transform Algorithm="http://www.w3.org/TR/1999/REC-xslt-19991116">
						<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
							<xsl:output encoding="UTF-8" indent="no" method="xml" omit-xml-declaration="yes"
							            standalone="yes" version="1.0"></xsl:output>
							<xsl:template match="@*|*">
								<xsl:copy>
									<xsl:apply-templates select="@*|*"></xsl:apply-templates>
									<xsl:apply-templates select="text()"></xsl:apply-templates>
								</xsl:copy>
							</xsl:template>
							<xsl:template match="text()">
								<xsl:choose>
									<xsl:when test="local-name(parent::*) = 'X509Certificate'">
										<xsl:value-of select="translate(normalize-space(.), ' ', '')"></xsl:value-of>
									</xsl:when>
									<xsl:otherwise>
										<xsl:value-of select="normalize-space(.)"></xsl:value-of>
									</xsl:otherwise>
								</xsl:choose>
							</xsl:template>
						</xsl:transform>
					</Transform>
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod>
				<DigestValue>...</DigestValue>
			</Reference>
		</SignedInfo>
		<SignatureValue>...</SignatureValue>
		<KeyInfo Id="idKeyInfo">
			<X509Data>
				<X509Certificate>...</X509Certificate>
			</X509Data>
		</KeyInfo>
	</Signature>
</Envelope>
```

It seems I would be able to add support by adding an object to `SignedXml.CanonicalizationAlgorithms`:

```
exports.XSLTCanonicalization = XSLTCanonicalization;

function XSLTCanonicalization() {
}

XSLTCanonicalization.prototype.process = function (node) {
  // XXX What to do here?
};

XSLTCanonicalization.prototype.getAlgorithmName = function () {
  return "http://www.w3.org/TR/1999/REC-xslt-19991116";
};
```

I can probably do the transformations using the browser's `XSLTProcessor`, but I am unsure how to get to the transformations at this point.

Do you have any suggestions?

**Comment by yaronn** [comment]
You would need to add the Canonicalization classes (at least the new one) a method loadParams (or alike) that loads the xml childs into local parameters. 
You also need to make SignedXml.prototype.addReference receive a new param transformProperties  and persist it in the Reference model. Than make findCanonicalizationAlgorithm get the params too and call loadPrams. Propogate to findCanonicalizationAlgorithm calls such as here https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L603.

So there seem to be some work to make it generic. If you know exactly what the xslt will always be you can hard code it in your transformation and save all of this (remember the code you wrote above can also reside in your app, does not need to run from xml-crypto). Or you could make some other simplifying assumptions (for example that there is only one xslt reference in the document and you can search for it in the whole xml, again from your code).

**Comment by jcassee** [comment]
Thanks, Yaron, this is very helpful. Good point about knowing the XSLT. In fact, it *is* fixed, so I can hard-code the translation in the project.

I will close this ticket now. (Sorry for using it as a support medium.)

Again, thank you!

**Comment by jcassee** [comment]
I have hard-coded the XSLT canonicalization class, and the references are verified. Thanks again for that tip!

Unfortunately, the signature to the SignedInfo section itself cannot yet be validated. The error message is ""invalid signature: the signature value 			s2gbf[...]v/A==		 is incorrect". This leads me to think that section is not canonized correctly. I am unsure whether this is a problem with the data, so I will try and fiddle with it some more.

**Comment by yaronn** [comment]
it's probably tricky to debug, and depends on how much flexibility you have with the other stack you interact with. maybe try a simple message (no whitespaces or namespaces) and see which step breaks (canonicalization, signing etc). you could also try to sign the full message with the other stack. make sure you use the same key / algo.
