### ISSUE TITLE
signature is empty

### ISSUE THREAD

**Issue by giggioz** [yaronn/xml-crypto#107]
Can you help me with this please?

```
var
    Parser = require('xmldom').DOMParser,
    sigXPath = '//*//*[local-name(.)=\'Signature\' and namespace-uri(.)=\'http://www.w3.org/2000/09/xmldsig#\']',
    xmlCrypto = require('xml-crypto');

var
    RECEIPT_TEST = '<?xml version="1.0" encoding="utf-8"?> <Receipt Version="1.0" ReceiptDate="2016-05-06T10:13:21Z" CertificateId="TEST_ID" ReceiptDeviceId="59a4dfa5-6485-4380-b990-9f08ae7b32a3"> <ProductReceipt Id="3d10cad5-b260-4b38-bae5-8749149d231e" AppId="2aa2a670-ffee-11e5-9a1b-b157c29e9099" ProductId="it.spaghettiinteractive.briscolapiu.noads_06" PurchaseDate="2016-05-06T10:13:21Z" ProductType="Durable" PurchasePrice="Euro2.990000"  /></Receipt>';


function handleError(error) {
    if (typeof error === 'string') {
        error = new Error(error);
    }
    console.log('error', error);
}

var options = {
    ignoreWhiteSpace: true,
    errorHandler: {
        fatalError: handleError,
        error: handleError
    }
};

var doc = new Parser(options).parseFromString(RECEIPT_TEST);
var signature = xmlCrypto.xpath(doc, sigXPath);

var certificateId = doc.documentElement.getAttribute('CertificateId');
console.log(certificateId); // <-- TEST_ID, OK.


console.log(signature); // <-- EMPTY ARRAY !!!

```

**Comment by yaronn** [comment]
I think you try to validate a signed receipt but RECEIPT_TEST does not contain any signature element inside it so the xpath in empty. for example see [this xml](https://github.com/yaronn/xml-crypto/blob/c19bcba71b6c7191756c56ae6d1637794bade3a4/test/static/windows_store_signature.xml) and [this test](https://github.com/yaronn/xml-crypto/blob/c19bcba71b6c7191756c56ae6d1637794bade3a4/test/signature-integration-tests.js#L66).

**Comment by giggioz** [comment]
Oh, that's clear, thanks.

By the way this is the xml msg i receive from windows store, looking at your [xml test](https://github.com/yaronn/xml-crypto/blob/c19bcba71b6c7191756c56ae6d1637794bade3a4/test/static/windows_store_signature.xml) i see that in my response the Signature part is missing.
May be you know why?

**Comment by yaronn** [comment]
not sure, I have not worked with the store myself. possibly windows store has a mechanism to sign receipt other than xml signatures, or this is a testing xml, not sure. I'm sure in a forum related to windows store someone will know about that.
