### ISSUE TITLE
How To Apply Custom Algorithm On CanonicalizationMethod?

### ISSUE THREAD

**Issue by vini-guerrero** [yaronn/xml-crypto#112]
Hey guys!

Can anyone help me on applying this signature pattern? I read the documentation, but I can't understand it correctly.
Should this work?
sign.canonicalizationAlgorithm = "http://www.w3.org/TR/xmldsig-core/"
Thanks in advance!

![pattern](https://cloud.githubusercontent.com/assets/18181786/17436394/0e963596-5aed-11e6-8183-590d86723c90.png)

**Comment by yaronn** [comment]
I think the canonicalization algorithm you want is http://www.w3.org/TR/2001/REC-xml-c14n-20010315. It is not officially supported yet but you might find a workaround in #102 .

**Comment by vini-guerrero** [comment]
Can u help on how to workaround this @yaronn ?

Should it be something like this into signed-xml.js:

`var SignedXml = require('xml-crypto').SignedXml;
var fs = require('fs');

function MyCanonicalization() {
    /*given a node (from the xmldom module) return its canonical representation (as string)*/
    this.process = function(node) {
        //you should apply your transformation before returning
        return "< x/>"
    }
    this.getAlgorithmName = function() {
        return "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"
    }
}

SignedXml.CanonicalizationAlgorithms["http://MyCanonicalization"] = MyCanonicalization
`

And my signature route.js is like:

`
        var sig = new SignedXml()
        sig.addReference("//*[local-name(.)='xxx' and namespace-uri(.)='http://www.portalfiscal.inf.br/nfe']")
        sig.signingKey = fs.readFileSync("./certificates/test.pem")
        sig.canonicalizationAlgorithm = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
        sig.computeSignature(xml, {
            location: { reference: "//*[local-name(.)='xxx']", action: "after" }
        });
        return sig.getSignedXml()`



How can I make this work properly? 
Thanks in advance!

**Comment by LoneRifle** [comment]
Fixed in #116
