### ISSUE TITLE
http://www.w3.org/TR/2001/REC-xml-c14n-20010315

### ISSUE THREAD

**Issue by ponyesteves** [yaronn/xml-crypto#113]
Hello @bjrmatos @yaronn, really need a hand with this. I read all the issues and PR relate to c14n and i am aware it's not supported yet. But perhaps someone could help me to solve this problem because i'm sure it's a namespace or whiterspace canonicalization diference that is bothering. 

``` xml
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <DigestValue>txO/Q5rCzp2FMT3FgOQfVzwCcFk=</DigestValue>
  </Reference>
</SignedInfo>
    <SignatureValue>wpnU9yX9RDxQsMYPAdiqR14EObYvsboXgXFatyPC7g3rcgSIT5VQdAdgKtUeKMpXi0hWDK/wyIsp53E0Jl9T46ooLFDZMuTYs7UAyiXX/MsvPGCYCmRK7uf0Cv3Wuu6bSCyzBgjQQ/sP130nYUGEXG9w4TxT7BAyanYhS4Fxl5A=</SignatureValue><KeyInfo><X509Data><X509IssuerSerial><X509IssuerName>CN=Correo Uruguayo - CA, OU=SERVICIOS ELECTRONICOS, O=ADMINISTRACION NACIONAL DE CORREOS, C=UY</X509IssuerName><X509SerialNumber>155761856642617054135126896023459966393</X509SerialNumber></X509IssuerSerial></X509Data></KeyInfo></Signature>
```

**I can' t verify this signature! I think it have something to do with the canonicalization process. The cannonXml (excC14N) would be:**

``` xml
<SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></CanonicalizationMethod>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></SignatureMethod>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></Transform>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></Transform>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></DigestMethod>
    <DigestValue>txO/Q5rCzp2FMT3FgOQfVzwCcFk=</DigestValue>
  </Reference>
</SignedInfo>
```

Would c14N cannon be the same? 

Thanks

**Comment by yaronn** [comment]
is this related to to other thread (order of transforms)?
do you control both sides (e.g. signature and verification) or verify a message from a third party?

The best way to debug is to start with the smallest xml sample, sign it in both platforms, and see when the digest differs. I would start with one transform only if possible to isolate the issue. Also try with a small xml with no white space or special characters.

**Comment by ponyesteves** [comment]
@yaronn it' s not related with the other issue I post #111, thought they have in common they drive me crazy to resolve them. I make it throught the problem and make a summary here cause may be it can't help other with same problem. 

as @bjrmatos comment on other post, the C14N (inclusive) and de EXC-C14N (exclusive) are very similar but have difference on the ise of namespaces. I 'm pasting and example of one of those differences. The c14n keeps namespaces of the context when selecting subsets of the document.



__I have this signed xml__

```xml
<ns0:CFE version="1.0" xmlns:ns0="http://cfe.dgi.gub.uy"><ns0:eTck><ns0:TmstFirma>2016-07-19T15:56:20-03:00</ns0:TmstFirma><ns0:Encabezado><ns0:IdDoc><ns0:TipoCFE>101</ns0:TipoCFE><ns0:Serie>A</ns0:Serie><ns0:Nro>1</ns0:Nro><ns0:FchEmis>2013-05-11</ns0:FchEmis><ns0:MntBruto>1</ns0:MntBruto><ns0:FmaPago>1</ns0:FmaPago><ns0:FchVenc>2013-08-21</ns0:FchVenc></ns0:IdDoc><ns0:Emisor><ns0:RUCEmisor>219999830019</ns0:RUCEmisor><ns0:RznSoc>DGI RUC PRUEBA NO CEDE</ns0:RznSoc><ns0:CdgDGISucur>1</ns0:CdgDGISucur><ns0:DomFiscal>1534 Avda. Daniel Fernandez Crespo</ns0:DomFiscal><ns0:Ciudad>Montevideo</ns0:Ciudad><ns0:Departamento>Montevideo</ns0:Departamento></ns0:Emisor><ns0:Receptor><ns0:TipoDocRecep>3</ns0:TipoDocRecep><ns0:CodPaisRecep>UY</ns0:CodPaisRecep><ns0:DocRecep>13353214</ns0:DocRecep><ns0:RznSocRecep>Juan Perez</ns0:RznSocRecep><ns0:DirRecep>18 de Julio 2016</ns0:DirRecep><ns0:CiudadRecep>Montevideo</ns0:CiudadRecep><ns0:DeptoRecep>Montevideo</ns0:DeptoRecep></ns0:Receptor><ns0:Totales><ns0:TpoMoneda>UYU</ns0:TpoMoneda><ns0:MntNoGrv>420</ns0:MntNoGrv><ns0:MntNetoIvaTasaMin>360</ns0:MntNetoIvaTasaMin><ns0:MntNetoIVATasaBasica>137704.92</ns0:MntNetoIVATasaBasica><ns0:IVATasaMin>10</ns0:IVATasaMin><ns0:IVATasaBasica>22</ns0:IVATasaBasica><ns0:MntIVATasaMin>36</ns0:MntIVATasaMin><ns0:MntIVATasaBasica>30295.08</ns0:MntIVATasaBasica><ns0:MntTotal>168816</ns0:MntTotal><ns0:CantLinDet>3</ns0:CantLinDet><ns0:MntPagar>168816</ns0:MntPagar></ns0:Totales></ns0:Encabezado><ns0:Detalle><ns0:Item><ns0:NroLinDet>1</ns0:NroLinDet><ns0:IndFact>3</ns0:IndFact><ns0:NomItem>Bananas</ns0:NomItem><ns0:Cantidad>40</ns0:Cantidad><ns0:UniMed>kg</ns0:UniMed><ns0:PrecioUnitario>4200</ns0:PrecioUnitario><ns0:MontoItem>168000</ns0:MontoItem></ns0:Item><ns0:Item><ns0:NroLinDet>2</ns0:NroLinDet><ns0:IndFact>2</ns0:IndFact><ns0:NomItem>Manzanas</ns0:NomItem><ns0:Cantidad>18</ns0:Cantidad><ns0:UniMed>kg</ns0:UniMed><ns0:PrecioUnitario>22</ns0:PrecioUnitario><ns0:MontoItem>396</ns0:MontoItem></ns0:Item><ns0:Item><ns0:NroLinDet>3</ns0:NroLinDet><ns0:IndFact>1</ns0:IndFact><ns0:NomItem>Papas</ns0:NomItem><ns0:Cantidad>12</ns0:Cantidad><ns0:UniMed>kg</ns0:UniMed><ns0:PrecioUnitario>35</ns0:PrecioUnitario><ns0:MontoItem>420</ns0:MontoItem></ns0:Item></ns0:Detalle><ns0:CAEData><ns0:CAE_ID>1234567890</ns0:CAE_ID><ns0:DNro>1</ns0:DNro><ns0:HNro>100</ns0:HNro><ns0:FecVenc>2012-12-31</ns0:FecVenc></ns0:CAEData></ns0:eTck><Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
    <DigestValue>xpXiLtg0nWejadP44Gm7ArFMk7Y=</DigestValue>
  </Reference>
</SignedInfo>
 <SignatureValue>ke8XBfPeT4OzEK5enxCJ6nK367fS9RFx007Yy+A8NAz1+cPIfSgqJhg68nesUCy/XlxbYkFAEU62GvhDg/XdiBFzkwMXac896pVFZr4S45v4FZX3YkosGIi64honz/2tvyUiN977Ek0HtLMoz6DVK5L/5FspvanZqJLEDqEGqJk=</SignatureValue><KeyInfo><X509Data><X509IssuerSerial><X509IssuerName>CN=Correo Uruguayo - CA, OU=SERVICIOS ELECTRONICOS, O=ADMINISTRACION NACIONAL DE CORREOS, C=UY</X509IssuerName><X509SerialNumber>155761856642617054135126896023459966393</X509SerialNumber></X509IssuerSerial></X509Data></KeyInfo></Signature></ns0:CFE>

```

__OUTPUT WITH C14N__ (inclusive)
note: it includes xmlns:ns0="http://cfe.dgi.gub.uy" 

```xml
<SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#" xmlns:ns0="http://cfe.dgi.gub.uy">
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></CanonicalizationMethod>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></SignatureMethod>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></Transform>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></Transform>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></DigestMethod>
    <DigestValue>xpXiLtg0nWejadP44Gm7ArFMk7Y=</DigestValue>
  </Reference>
</SignedInfo>
```

__OUTPUT WITH EXC-C14N__ (inclusive)

note: the difference is that c14n includes ancester namespace xmlns:ns0="http://cfe.dgi.gub.uy" and exc-c14n don't


```xml
<SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
  <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></CanonicalizationMethod>
  <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></SignatureMethod>
  <Reference URI="">
    <Transforms>
      <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"></Transform>
      <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></Transform>
    </Transforms>
    <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></DigestMethod>
    <DigestValue>xpXiLtg0nWejadP44Gm7ArFMk7Y=</DigestValue>
  </Reference>
</SignedInfo>
```

**Comment by vini-guerrero** [comment]
@ponyesteves How did u include CanonicalizationMethod Algorithm="**http://www.w3.org/TR/2001/REC-xml-c14n-20010315** ?
Can u share that implementation blob?

**Comment by ponyesteves** [comment]
Sure @vini-guerrero , it's more a hard coded implementation for this context.  The app must sign doc's to send to a gob department of Uruguay, the accept both c14n a exc-c14n. So in that case y sign straight away with exc-c14n. The problem was with docs or replies coming from them, most of witch are cononicalizated with http://www.w3.org/TR/2001/REC-xml-c14n-20010315, for document digest (transformation) and signature also. With the transform and the digest the lib as it is (i mean using exc-c14n as if it was c14n) works fine. As I said the problem is when using subsets, in this case when selecting the singInfo.  
So based on the code samples that I post in this conversation, what I did is this. When checking signature value i added a conditional to check if it c14n and add the xmlns i need 
```javascript
SignedXml.prototype.validateSignatureValue = function() {
  var signedInfo = utils.findChilds(this.signatureNode, "SignedInfo")
  if (signedInfo.length==0) throw new Error("could not find SignedInfo element in the message")
  if(this.canonicalizationAlgorithm == 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315'){
    var options = {defaultNs: 'xmlns:ns0="http://cfe.dgi.gub.uy"'} //TODO: agrego esta atributo para las firmas con c14n inclusiva..esto hay que revisarlo y mejorarlo
  }
   
```

And then in exclusive-canonicalization.js  I check and add the xmlns if exists

**Comment by vini-guerrero** [comment]
@ponyesteves Thanks man! I've been analysing the code trying to understand where the implementations should be, that was very helpful, I'm using an online validator from brazil government, I think I'm almost there, correct a few tags and the validation went one tag higher level.
Just one more question about the signature changes...
Would you happen to know if the changes I wanna do should be applied to "exclusive-canonicalization.js" too?
I need my signature to be exact like this:


`<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#NFe41121108187168000160557780005200771000000202">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>CISveLMqVUSC+kahmRJWm3txC9U=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>
...
</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>
...
</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>`

**Comment by vini-guerrero** [comment]
@ponyesteves Thanks man! I've been analysing the code trying to understand where the implementations should be, that was very helpful, I'm using an online validator from brazil government, I think I'm almost there, correct a few tags and the validation went one tag higher level.
Just one more question about the signature changes...
Would you happen to know if the changes I wanna do should be applied to "exclusive-canonicalization.js" too?
I need my signature to be exact like this:

<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#NFe41121108187168000160557780005200771000000202">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>CISveLMqVUSC+kahmRJWm3txC9U=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>...</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>...</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>

**Comment by vini-guerrero** [comment]
@ponyesteves Thanks man! I've been analysing the code trying to understand where the implementations should be, that was very helpful, I'm using an online validator from brazil government, I think I'm almost there, correct a few tags and the validation went one tag higher level.
Just one more question about the signature changes...
Would you happen to know if the changes I wanna do should be applied to "exclusive-canonicalization.js" too?
I need my signature to be exact like this:




'<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#NFe41121108187168000160557780005200771000000202">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>CISveLMqVUSC+kahmRJWm3txC9U=</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>
...
</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>
...
</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>'

**Comment by vini-guerrero** [comment]
@ponyesteves Thanks man! I've been analysing the code trying to understand where the implementations should be, that was very helpful, I'm using an online validator from brazil government, I think I'm almost there, correct a few tags and the validation went one tag higher level.
Just one more question about the signature changes...
Would you happen to know if the changes I wanna do should be applied to "exclusive-canonicalization.js" too?
I need my signature to be exact like this:

<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#NFe41121108187168000160557780005200771000000202">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>...</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>...</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>...</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>

**Comment by vini-guerrero** [comment]
@ponyesteves Thanks man! I've been analysing the code trying to understand where the implementations should be, that was very helpful, I'm using an online validator from brazil government, I think I'm almost there, correct a few tags and the validation went one tag higher level.
Just one more question about the signature changes...
Would you happen to know if the changes I wanna do should be applied to "exclusive-canonicalization.js" too?
I need my signature to be exact like this:

<Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="#NFe41121108187168000160557780005200771000000202">
<Transforms>
<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
<Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
</Transforms>
<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
<DigestValue>...</DigestValue>
</Reference>
</SignedInfo>
<SignatureValue>...</SignatureValue>
<KeyInfo>
<X509Data>
<X509Certificate>...</X509Certificate>
</X509Data>
</KeyInfo>
</Signature>



I replaced the Algorithm in the js file for http://www.w3.org/TR/2001/REC-xml-c14n-20010315 but I still need the same value inside Transform tag, how can I get that?
Thanks in advance!

**Comment by vini-guerrero** [comment]
@ponyesteves Thanks man! I've been analysing the code trying to understand where the implementations should be, that was very helpful, I'm using an online validator from brazil government, I think I'm almost there, correct a few tags and the validation went one tag higher level.
Just one more question about the signature changes...
Would you happen to know if the changes I wanna do should be applied to "exclusive-canonicalization.js" too?
I need my signature to be exact like this:

![sign](https://cloud.githubusercontent.com/assets/18181786/17624242/38176c5e-607a-11e6-8a3d-9d9c16d9daa5.png)


I replaced the Algorithm in the js file for http://www.w3.org/TR/2001/REC-xml-c14n-20010315 but I still need the same value inside Transform tag, how can I get that?
Thanks in advance!

**Comment by ponyesteves** [comment]
@vini-guerrero glad to by helpful

In my particular case I use exc-c14n to sign so I didn't have to implement c14n(http://www.w3.org/TR/2001/REC-xml-c14n-20010315 ) for the signature case. Though I did have to implement it for validating c14n signatures. 

But perhaps these approach can help you.. also check issue #24 

To add the algorithm to transformation you should  pass it to the function addReference like these. 
```javascript
      sig.addReference("//*[local-name(.)='CFE']", ["http://www.w3.org/2000/09/xmldsig#enveloped-signature", "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"])
```  
To implemente the algorithm you should add http://www.w3.org/TR/2001/REC-xml-c14n-20010315 key to this object point it to yooure implementacion
``` javascript
SignedXml.CanonicalizationAlgorithms = {
  'http://www.w3.org/2001/10/xml-exc-c14n#': ExclusiveCanonicalization,
  'http://www.w3.org/2001/10/xml-exc-c14n#WithComments': ExclusiveCanonicalizationWithComments,
  'http://www.w3.org/2000/09/xmldsig#enveloped-signature': EnvelopedSignature,
  'http://www.w3.org/TR/2001/REC-xml-c14n-20010315': YourCanonicalizationAlgorithm
}
```

Hope it help!

After you succeed please share, it may contribute to include support to these algorithm !

**Comment by bjrmatos** [comment]
@ponyesteves @vini-guerrero sorry for not being able to respond your comments, i promise to find the time to work on your issues, maybe we can work together to implement `xml-c14n` 😄

**Comment by ponyesteves** [comment]
@bjrmatos no problem! Looking forward to give support to c14n. Thougth I must say that the w3c XML documentation is very heavy to read and understand!

**Comment by danieljoppi** [comment]
ow ...I really need this for Brazilian Electronic Invoice ...

**Comment by ponyesteves** [comment]
Hi @yaronn @bjrmatos, 
          would you consider making a branch to start working on c14n support? I monkey patched the lib and is working for me. But I'm willing to contribute to this support out of the box and official. Sure @vini-guerrero and  @danieljoppi could help also.

**Comment by danieljoppi** [comment]
@ponyesteves look my PR #116

**Comment by ponyesteves** [comment]
Hi @danieljoppi I take a quick look to de PR #116. I can see you copy the code of exclusive canonicalization and rename it to c14n (that'e great for a start) but can't distinguish the function modificaciones that implements c14n.  In my recent experience there are at minimum to big differences
1) How c14n handles namespaces hierarchy 2) also have to do with xmlns attribute .

Does de PR #116 have specific code for c14n implementation? If so, can you mark those differences. It would be really helpfull to analice the PR. 

  
thanks,

**Comment by danieljoppi** [comment]
@ponyesteves then c14n (Canonical XML) specifies a standard serialization of XML that ... and the c14n Exclusive (Exculsive Caninical XML) extends the c14n, but ignores all attributes that were not defined in `inclusiveNamespacesPrefixList` [exclusive-canonicalization.js#L97](https://github.com/yaronn/xml-crypto/blob/master/lib/exclusive-canonicalization.js#L97)

**Comment by ponyesteves** [comment]
@danieljoppi can you take a look to this issue #115

**Comment by bjrmatos** [comment]
as far i can tell (when i was reading the W3C C14n docs) there are others differences in respect with namespaces

**Comment by danieljoppi** [comment]
https://www.w3.org/TR/2002/REC-xml-exc-c14n-20020718/#sec-Specification

**Comment by ponyesteves** [comment]
So, for the 1 bullet of the doc @danieljoppi shared, its necessary to process the subset with the hole xml doc for context. I've hardcoded that to work for my specific case. But to really give support the code must read all ancestors and check for attributes when using sub set. 

I'm having truble understanding bullet 3. 

![image](https://cloud.githubusercontent.com/assets/4960589/18256218/bb61d7e0-7388-11e6-8247-99d6be722e1a.png)

**Comment by danieljoppi** [comment]
The **C14N Exclusive** was worked in `xml-crypto` ... this example show us *only* the differences between **C14N** and **C14N Exclusive**.

@ponyesteves you can propose a XML to be tested for the C14N algorithm? 

In my case I made a simple XML (**NFe** - *Brazilian Electronic Invoice*) ... and the signature already was tested and approve by the [NFe Validator](https://www.sefaz.rs.gov.br/nfe/NFE-VAL.aspx).

**Comment by bjrmatos** [comment]
looking at the code, i'm still not sure if it is 100% compliant with the spec (will need a carefuly review and more tests cases to be sure) but it is definitely the right start.

@ponyesteves Have you tried the C14N implementation against your case? let me know if it works for you, the @danieljoppi 's comment about `inclusiveNamespacesPrefixList` is correct. 

`c14n` and `exc14n` shares a lot and only differs in some things, so i will not be surprised if the code of @danieljoppi works for your case.

**Comment by ponyesteves** [comment]
I'll give it a try this week and comment the result's.

**Comment by ponyesteves** [comment]
@danieljoppi @bjrmatos  I tried the implementation and my test are failing in validating Uruguayan gob singed xml. As I explained in #115 with code example . I'm not sure if the Uruguayan implementation of the standard is correct (have my doubts) but unfortunately I must adapt to them and not otherwise.  
Nevertheless Daniel's implementation doesn't break anything so I think it' s great to work on it.  
This XML contains a valid signature checked. It may be usefull for test case.  Look the referencia tag... (detailed explanation #115)

```xml
<ns0:CFE xmlns:ns0="http://cfe.dgi.gub.uy" version="1.0"><ns0:eResg><ns0:TmstFirma>2016-09-01T11:08:39-03:00</ns0:TmstFirma><ns0:Encabezado><ns0:IdDoc><ns0:TipoCFE>182</ns0:TipoCFE><ns0:Serie>A</ns0:Serie><ns0:Nro>1</ns0:Nro><ns0:FchEmis>2016-09-01</ns0:FchEmis></ns0:IdDoc><ns0:Emisor><ns0:RUCEmisor>219999830019</ns0:RUCEmisor><ns0:RznSoc>DGI</ns0:RznSoc><ns0:CdgDGISucur>1</ns0:CdgDGISucur><ns0:DomFiscal>FERNANDEZ CRESPO AVDA. DANIEL 1534</ns0:DomFiscal><ns0:Ciudad>MONTEVIDEO</ns0:Ciudad><ns0:Departamento>MONTEVIDEO</ns0:Departamento></ns0:Emisor><ns0:Receptor><ns0:TipoDocRecep>2</ns0:TipoDocRecep><ns0:CodPaisRecep>UY</ns0:CodPaisRecep><ns0:DocRecep>180067050012</ns0:DocRecep><ns0:RznSocRecep>KENT BURGOS GUSTAVO RANDERS</ns0:RznSocRecep><ns0:DirRecep>RODO, JOSE ENRIQUE</ns0:DirRecep><ns0:CiudadRecep>PALMITAS</ns0:CiudadRecep></ns0:Receptor><ns0:Totales><ns0:TpoMoneda>UYU</ns0:TpoMoneda><ns0:MntTotRetenido>55000</ns0:MntTotRetenido><ns0:CantLinDet>2</ns0:CantLinDet><ns0:RetencPercep><ns0:CodRet>2183165</ns0:CodRet><ns0:ValRetPerc>55000</ns0:ValRetPerc></ns0:RetencPercep></ns0:Totales></ns0:Encabezado><ns0:Detalle><ns0:Item><ns0:NroLinDet>1</ns0:NroLinDet><ns0:RetencPercep><ns0:CodRet>2183165</ns0:CodRet><ns0:Tasa>50</ns0:Tasa><ns0:MntSujetoaRet>22000</ns0:MntSujetoaRet><ns0:ValRetPerc>11000</ns0:ValRetPerc></ns0:RetencPercep></ns0:Item><ns0:Item><ns0:NroLinDet>2</ns0:NroLinDet><ns0:RetencPercep><ns0:CodRet>2183165</ns0:CodRet><ns0:Tasa>50</ns0:Tasa><ns0:MntSujetoaRet>88000</ns0:MntSujetoaRet><ns0:ValRetPerc>44000</ns0:ValRetPerc></ns0:RetencPercep></ns0:Item></ns0:Detalle><ns0:Referencia><ns0:Referencia xmlns="http://cfe.dgi.gub.uy"><ns0:NroLinRef>1</ns0:NroLinRef><ns0:TpoDocRef>111</ns0:TpoDocRef><ns0:Serie>A</ns0:Serie><ns0:NroCFERef>25</ns0:NroCFERef><ns0:FechaCFEref>2016-09-01</ns0:FechaCFEref></ns0:Referencia><ns0:Referencia xmlns="http://cfe.dgi.gub.uy"><ns0:NroLinRef>2</ns0:NroLinRef><ns0:TpoDocRef>111</ns0:TpoDocRef><ns0:Serie>A</ns0:Serie><ns0:NroCFERef>30</ns0:NroCFERef><ns0:FechaCFEref>2016-09-01</ns0:FechaCFEref></ns0:Referencia></ns0:Referencia><ns0:CAEData><ns0:CAE_ID>90110002917</ns0:CAE_ID><ns0:DNro>1</ns0:DNro><ns0:HNro>100</ns0:HNro><ns0:FecVenc>2016-12-31</ns0:FecVenc></ns0:CAEData></ns0:eResg><Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
<SignedInfo>
<CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
<Reference URI="">
  <Transforms>
    <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
    <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
  </Transforms>
  <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
  <DigestValue>UY+mVfKuRQm7zK7TTr22rj/77Wc=</DigestValue>
</Reference>
</SignedInfo>
  <SignatureValue>kmr/37zalpoNdqVOQIYD6xeuJso+O1lSXtdHnM8BjGN6kHcORm7otsVCC8XH/BN+O4G4Majle416SQ8HZJQgCdWNXkxPd0oMfHbd7vVdeXks87EYrpV5pTg3O2isaRHOsYJikyDyux01CoPMf+6G0VgWH6Wag7B7Up4bW2Eou30=</SignatureValue><KeyInfo><X509Data><X509IssuerSerial><X509IssuerName>CN=Correo Uruguayo - CA, OU=SERVICIOS ELECTRONICOS, O=ADMINISTRACION NACIONAL DE CORREOS, C=UY</X509IssuerName><X509SerialNumber>155761856642617054135126896023459966393</X509SerialNumber></X509IssuerSerial></X509Data></KeyInfo></Signature></ns0:CFE>
```

**Comment by bjrmatos** [comment]
@ponyesteves is it possible that you can post the entire XML document in #115 ? in my experience it will be very useful.

**Comment by ponyesteves** [comment]
Sure @bjrmatos, i've just post it on #115

**Comment by emueller-sage** [comment]
I have also needed this canonicalization and have added the method from my code as follows. Essentially I collect the namespaces and then invoke exclusive canonicalization. For placing this into xml-crypto, finding the exclusive canonicalization within the `process` method should be simplified. The implementation below can change `node` by adding some namespace attributes.

```
// for canonicalization "http://www.w3.org/TR/2001/REC-xml-c14n-20010315": collect namespaces of ancestors
function enhanceNS(node) {
	var current = node;
	var result = {
			inclusiveNamespacesPrefixList: []
	}
	var prefixes = result.inclusiveNamespacesPrefixList;
	while (current) {
		if (current.attributes) {
			for (var i = 0; i < current.attributes.length; ++i) {
			    var attr = current.attributes[i];
			    //only look at namespace definition attributes
			    if (attr.prefix === "xmlns") {
			    	if (prefixes.indexOf(attr.localName) < 0) {
			    		prefixes.push(attr.localName);
			    		if (current != node) {
			    			node.setAttributeNS("http://www.w3.org/2000/xmlns/", attr.name, attr.value);
			    		}
			    	}			    	
			    } else if (attr.name === "xmlns") { // default name space
			    	if (!("defaultNs" in result)) result.defaultNs = attr.value;
			    }
			}
		}		
		current = current.parentNode;
	}
	return result;
}


function NonExclusiveCanonicalization() {
	  /* Non-exclusive Canonicalization as "http://www.w3.org/TR/2001/REC-xml-c14n-20010315" 
	   * differs from exclusive canonicalization by namespace handling */ 
	  this.process = function(node) {
		  var options = enhanceNS(node, true);
		  var algo = SignedXml.CanonicalizationAlgorithms["http://www.w3.org/2001/10/xml-exc-c14n#"]; 
		  return new algo().process(node, options);
	  }
	   this.getAlgorithmName = function() {
	    return "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"
	  }
}

SignedXml.CanonicalizationAlgorithms["http://www.w3.org/TR/2001/REC-xml-c14n-20010315"] = NonExclusiveCanonicalization;
```

**Comment by danielfungca** [comment]
Gents and all,

I have the same problem with ADFS v4. A Third party is sending me a SAML message with http://www.w3.org/TR/2001/REC-xml-c14n-20010315 Canonicalization and ADFS out of the box does not seem to support it. Does anyone here know / have had this problem and how did you fix it do ADFS works with this Canonicalization method.

Thanks in advance.

**Comment by Hinaser** [comment]
Hi @danielfungca 

I have a similar issue and I am getting closer to the solution.
I read specification of http://www.w3.org/TR/2001/REC-xml-c14n-20010315 carefully and found that xml-crypto needs more lines to be compat with this non-exclusive c14n method.

I'll send PR for this issue soon.

**Comment by Hinaser** [comment]
In case you want to try my PR before being merged, run the below command to install my one.
```
npm install --save https://github.com/Hinaser/xml-crypto.git#patch-for-non-exclusive-c14n
```

[xml-crypto-trying.zip](https://github.com/yaronn/xml-crypto/files/2085280/xml-crypto-trying.zip)

You can try demo by unzip the above file and execute command as below:
```
cd xml-crypto-trying
npm install
node main.js
```

You can look into `main.js` if you want to know what it does.
