### ISSUE TITLE
Canonicalization not working for some listed methods

### ISSUE THREAD

**Issue by omaralqady** [yaronn/xml-crypto#124]
`http://www.w3.org/TR/2001/REC-xml-c14n-20010315` and `http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments` throw an error that looks like:

```
Error: canonicalization algorithm 'http://www.w3.org/TR/2001/REC-xml-c14n-20010315#With│/work/dev/xmldsig/node_modules/xml-crypto/lib/signed-xml.js:292                       
Comments' is not supported 
```

when I set them as the canonicalization algorithms, even though they're listed in the list of supported algorithms.

The exclusive method works fine for me, but not this one.

**Comment by bjrmatos** [comment]
@omaralqady i recently merged this [PR](https://github.com/yaronn/xml-crypto/pull/116) where `c14n` implementation was done, however is not published in npm yet, there are some little changes that has to be made (about keeping consistency with other implementations) but until that time you can install `xml-crypto` directly from github `npm install yaronn/xml-crypto` to get access to this feature.

**Comment by omaralqady** [comment]
@bjrmatos Thank you, it does work in that version indeed :+1:
