### ISSUE TITLE
Apply multiple canonicalization methods?

### ISSUE THREAD

**Issue by omaralqady** [yaronn/xml-crypto#125]
I'm working with a proprietary system that needs the following:

> 1. For the purpose of generating the digest of the main message, the inclusive canonicalization
algorithm must be used.
>** This method of canonicalization of the main message is not (always) explicitly indicated in the XML messages.
> 2. For the purpose of generating the signature value, the exclusive canonicalization algorithm
must be used.

Can this method be applied using the current design of `xml-crypto`? If not, can it be extended to do it? I'm willing to work on a PR to allow this if it's doable under the current design.

**Comment by bjrmatos** [comment]
yes, according to your specifications, you need to use `exc-c14n` as the canonicalization method for the signature.

`exc-c14n` is the default method used, but if you want to change to another you can:

```js
var sig = new SignedXml()
sign.canonicalizationAlgorithm = '[PUT THE URI OF YOUR METHOD HERE]' //ex: 'http://www.w3.org/2001/10/xml-exc-c14n#'
```

and for the canonicalization in the digest of the reference you can pass an array of inclusive namespaces to `.addReference`, see this line to know https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L426 the correct order of the arguments.

**Comment by omaralqady** [comment]
@bjrmatos Doesn't `exc-c14n` mean exclusive while the specs I posted refer to inclusive for the main message?

* Also on an unrelated note, I have a couple of other questions that are not particularly issues, is there another way I can communicate with you without opening an issue here so as not add a non-issue to the list? (What I want to do is generate a signature without adding a reference ID to the digested element, and there doesn't seem to be an option to do that. I'm willing to work on adding this if you think it will be useful and it would be possible to merge a PR for it)

**Comment by bjrmatos** [comment]
> For the purpose of generating the signature value, the exclusive canonicalization algorithm
> must be used.

@omaralqady according to this, you need to use exclusive canonicalization to generate the signature and inclusive canonicalization to generate a digest (hash) of your message. one thing is applying a canonicalization method to your main message (a reference) in order to get a digest and another is applying a canonicalization method to all digest of references to get the final signature.



> What I want to do is generate a signature without adding a reference ID to the digested element

sorry about the state of documentation in the repository, there's so much to do to improve it.. but this is possible, i'm assuming that you want a reference to the whole XML document, which means a reference like this <Reference URI=""> (without a URI value).



> I have a couple of other questions that are not particularly issues, is there another way I can communicate with you without opening an issue here so as not add a non-issue to the list?

yes, you can email me at bjrmatos@gmail.com , but sorry if you don't have a response immediately, i don't have so much time, please try to send me an example of the XML you want to generate (maybe the example is in the document of the spec that you are following) to speed things.

**Comment by omaralqady** [comment]
@bjrmatos The document would have to look like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<CertainReq xmlns="privateNamespaceURL" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" version="3.3.1">
    <createDateTimestamp>2017-02-24T00:20:35.280Z</createDateTimestamp>
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
        <SignedInfo>
            <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
            <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
            <Reference URI="">
                <Transforms>
                    <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                </Transforms>
                <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <DigestValue>sR4Y3aRSxUyvN5FO3VfdpMOwE2ChYiYLsiBztQOPLb4=</DigestValue>
            </Reference>
        </SignedInfo>
        <SignatureValue>jIRm6JGD0ABLPqn+UMn/QRc9VtGLkbuecKhm3kThAEB9WtYazIscZPUQBjdUasT92NleEr0bXmmW
V5DVilJ46JjC2zpaehjKKECX7LkbnswiwULn+d/VcxITnTeWM25M6o/fMpeQQjUibXPfn9AgWYYX
ZMHQlsJNwXnNNjqvmq43QnYrLWFPanjgwaM2CoaGrVoTrWScWxFGCBOCDulPoPALvYayG1jpk4EY
8W4yAMEhpZTnkxMlm8+egf7Jpw+N9N3asUn84JYu7BOmhxXc6sjT1kU2VvV3ANB0pX+01Fv841bv
zzJh4ehCaEwG4CECQilaI09bSOn9oUyUg/6R6A==</SignatureValue>
        <KeyInfo>
            <KeyName>00CDA7F82E4CBA8F5A3F2736BE02DC23204485C3</KeyName>
        </KeyInfo>
    </Signature>
</CertainReq>
```

The signature isn't valid for this example, because I have to change a few things within it, I can't share the actual request but this is the format that I need to have.

I generate the `KeyName` using a customized `KeyInfoProvider` as stated in the docs and it works properly.

The problem I have now is that I get an ID like this (as an attribute in the `CertainReq`): `Id="_0"` and the `Reference` has a URI: `URI="#_0"`.

So what options do I need to set/change to get such a format?

I really appreciate your help with this, thank you for your effort and your time.

**Comment by bjrmatos** [comment]
you will need to use something like this:

```js
signGenerator.addReference(
    // reference to the whole document
    '/*',
    // transforms to apply to reference
    [
      'http://www.w3.org/2000/09/xmldsig#enveloped-signature',
      // 'http://www.w3.org/2001/10/xml-exc-c14n#' (according to your spec you need inclusive canonicalization here, but i don't know if it is canonicalization based on c14n or exc-c14n)
    ],
    // digest algorithm
    'http://www.w3.org/2001/04/xmlenc#sha256',
   // let this option empty
    '',
   // let this option empty
    '',
   // this option is for inclusive namespaces, (according to your spec you will need this option, which is an array of xml namespaces) i'm using just an empty value for the example 
    '',
    // this boolean tells xml-crypto to not generate a URI with a value, URI=""
    true
  );
```

**Comment by omaralqady** [comment]
@bjrmatos Thank you for your help it finally works :) :+1: 

Also, I saw you just did a new release to NPM, and I'm assuming the new release includes the algorithms that were only available in the github repo, is that correct?

**Comment by bjrmatos** [comment]
@omaralqady glad that it works!, yes, new version includes the new changes

**Comment by phra** [comment]
> I generate the KeyName using a customized KeyInfoProvider as stated in the docs and it works properly.

@omaralqady can you share the actual code to add the keyinfo/keyname elements?

**Comment by bjrmatos** [comment]
@phra you can take a look [here](https://github.com/yaronn/xml-crypto/issues/47#issuecomment-126144393)

**Comment by phra** [comment]
@bjrmatos thanks.

**Comment by omaralqady** [comment]
@phra I just saw your comment. If the sample above didn't work for you, let me know.

**Comment by phra** [comment]
everything works. we will release an open source library soon at work based on `xml-crypto`.
for future references, my code looks like this (in the comment the code for debug signature problems):
```typescript
export function signXML(xml: any) {
  const sig = new SignedXml()
  const entryPoint = '/*'
  const transformers = ['http://www.w3.org/2000/09/xmldsig#enveloped-signature', 'http://www.w3.org/2001/10/xml-exc-c14n#']
  const xmlenc = 'http://www.w3.org/2001/04/xmlenc#sha256'
  const signatureAlgorithm = 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
  const MyKeyInfo = function(this: any, key: string) {
    this.getKeyInfo = (privateKey: any, prefix: string) => {
      return `<KeyName>${KEYNAME}</KeyName>`
    }
  } as any

  sig.addReference(entryPoint, transformers, xmlenc, void 0, void 0, void 0, true)
  sig.keyInfoProvider = new MyKeyInfo(PRIVATE_KEY)
  sig.signatureAlgorithm = signatureAlgorithm
  sig.signingKey = PRIVATE_KEY
  sig.computeSignature(xml)
  const res = sig.getSignedXml()
  // verifyOwnSignature(res, xml)
  return res
}

// export function verifyOwnSignature(res: any, xml: string) {
//   var doc = new DOMParser().parseFromString(res)
//   var signature = xpath(doc, "//*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0]
//   var sx = new SignedXml()
//   sx.keyInfoProvider = new FileKeyInfo('cert.pem')
//   sx.loadSignature(signature)
//   var result = sx.checkSignature(xml)
//   if (!result) {
//     console.warn(result, sx.validationErrors)
//   }
// }
```
