### ISSUE TITLE
Issue with custom keyInfoProvider

### ISSUE THREAD

**Issue by an-sush** [yaronn/xml-crypto#127]
Hello,

I am using xml-crypto to validate signature. If I have the public key as local file, it works fine with default settings (as shown in example). But when I have to read it from a S3 bucket, I use a custom KeyInfo implementation and it failed:

```
var sig = new SignedXml();
sig.keyInfoProvider = new S3KeyInfo(key);
sig.loadSignature(signature[0]);
var validated = sig.checkSignature(payload);
```

```
function S3KeyInfo(key) {
	this.key= key;
  this.getKeyInfo = function(key, prefix) {
	prefix = prefix || ''
	prefix = prefix ? prefix + ':' : prefix
    return "<" + prefix + "X509Data></" + prefix + "X509Data>"
  }
  this.getKey = function(keyInfo) {
  	var s3 = new AWS.S3();
  	s3.getObject({Bucket: 'my-bucket', Key: this.key},
	  function (error, data) {
	    if (error != null) {
	      console.log("Failed to retrieve an object: " + error);
	    } else {
	      console.log("Loaded " + data.ContentLength + " bytes");
	      return data;
	    }
	  }
	); 
  }
```

When I run this in my lambda, I get error:

> Error: key info provider could not resolve key info 
> at SignedXml.checkSignature (/var/task/node_modules/xml-crypto/lib/signed-xml.js:260:31)

Please help me how to call the SignedXml by reading public cert from S3 (or string content) instead of local

**Comment by bjrmatos** [comment]
hmm, key info providers are expected to be synchronous (a limitation), this means that you can't fetch your key from S3 in the `getKey` method (because `s3.getObject` is asynchronous), to solve your issue try to read/fetch your key before creating your key info provider.

i'm closing this because is not an issue, but feel free to continue the conversation.
