### ISSUE TITLE
Question: Sign xml using Electron app

### ISSUE THREAD

**Issue by betoharres** [yaronn/xml-crypto#128]
Hello, first of all, great lib, thanks for putting the effort on this ❤️ 

Considering that I've never used electron and few node libraries, I'd like some insight about if would be possible to sign local xml using your library through an Electron app, do you see that being possible? 
I'm developing a react-redux app in the browser and in order to sign the xml I'd have to create a Java app running localhost through SSL, but then I realized that I could use Electron.

What do you think? Thanks in advance!

**Comment by bjrmatos** [comment]
@betoharres yes! it should be possible to sign xml files inside of an electron application. (since electron is like a node.js runtime by itself and has all node.js APIs available) so i would say that you use case is totally possible 👍 😄

**Comment by betoharres** [comment]
@bjrmatos Hey, thanks a lot for your response! I appreciated 😄   I'll close this now, good luck with the library! 🎉
