### ISSUE TITLE
Q: Openssl requirement

### ISSUE THREAD

**Issue by betoharres** [yaronn/xml-crypto#129]
> A pre requisite it to have openssl installed and its /bin to be on the system path. I used version 1.0.1c but it should work on older versions too.

Hey, I was wondering if `openssl` is only required for key(.pem) generation or it's required for the library code? I ask because I'm using forge to load and manage certificates and get the private key and I'd like to know if a windows user, for example, would have to download and install the `openssl` library.
Thanks in advance 😄

**Comment by bjrmatos** [comment]
@betoharres hi! `openssl` is just a recommendation to work better with .der,.pem files, so you're right, users don't need to donwload or install `openssl` manually 👍 

we use the node.js `crypto` API which in fact comes with bundled version of `openssl` installed but this is transparent and users don't need to install it explicitly

**Comment by betoharres** [comment]
Yeah, just as I expected. Thanks a lot for quick response!
