### ISSUE TITLE
not able to sign messages with rsa256 digest

### ISSUE THREAD

**Issue by phra** [yaronn/xml-crypto#141]
hi,

I'm trying to sign my data with http://www.w3.org/2001/04/xmlenc#sha256 as my digest algorithm, but I could not find a way to configure it without updating the source code at https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L442 in:
```
"digestAlgorithm": digestAlgorithm ? digestAlgorithm : "http://www.w3.org/2001/04/xmlenc#sha256",
```

**Comment by yaronn** [comment]
Per the documentation for addReference in README:

`addReference(xpath, [transforms], [digestAlgorithm])`

**Comment by phra** [comment]
@yaronn thanks for that. i also need the ability to encrypt and decrypt messages, are you working on that part?

**Comment by yaronn** [comment]
I am not planing to work on this in the near future.
