### ISSUE TITLE
Wish: Changelog

### ISSUE THREAD

**Issue by markstos** [yaronn/xml-crypto#144]
Especially for security and crypto-related modules, it's nice to have a clear Changelog to understand what changed between versions.

http://keepachangelog.com/ is a good reference.

The Github "Releases" feature is an easy way to keep a changelog. You can use `hub release create` to create a release and add some notes for it.

**Comment by markstos** [comment]
Reading the commit log is generally not a good substitute, and in the most recent release, it appears most changes happened in a commit named simply "fix multiple issues".

**Comment by LoneRifle** [comment]
This is now generally adhered to.
