### ISSUE TITLE
Problems verifying a SAML2 token signature

### ISSUE THREAD

**Issue by einarjohnson** [yaronn/xml-crypto#153]
I was wondering if you could help me out with a problem I am having with verifying a signature inside a SAML2 token from an Icelandic provider named Audkenni. 
I have attached the token unchanged as we receive it. (base64 encoded)
According to the IdentityProvider the certificate inside the SAML token should be verified against their CA chain. 
My first task was to export this p7b file to a PEM certificate chain list which I then provide to the xml-crypto lib. My code is roughly like this:
```
var select = require('xml-crypto').xpath
    , dom = require('xmldom').DOMParser
    , SignedXml = require('xml-crypto').SignedXml
    , FileKeyInfo = require('xml-crypto').FileKeyInfo  
    , fs = require('fs') 
    , xpath = require('xpath') 
    , verifier = require("node-openssl-verify-cert");
// Read the test token 
var buf = new Buffer(fs.readFileSync('testtoken.txt').toString(), 'base64');
var xml = new Buffer(buf, 'base64').toString('utf8').toString();
var doc = new dom().parseFromString(xml);

// Verify the signature using chained certificate
var signature = select(doc, "/*/*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0];
var sig = new SignedXml();
sig.keyInfoProvider = new FileKeyInfo("./certs/Audkenni_Chain.pem");
sig.loadSignature(signature);
var res = sig.checkSignature(xml);
if (!res) console.log(sig.validationErrors);
```

I have pretty much tried everything here, the checkSignature function always fails. What I find even more strange is that I can't even get this SAML2 token to verify using a public tool like
https://www.samltool.com/validate_response.php

I am starting to suspect that I am providing the wrong certificate into xml-crypto. The Identityprovider lists all their certificates here: https://www.audkenni.is/adstod/skilriki-kortum/skilrikjakedjur/
I have tried feeding each of these certificates (PEM encoded)  into the keyinfoprovider without any luck so I am pretty much stranded with this.  Any help/comments would be greatly appreciated.

**Comment by einarjohnson** [comment]
[testtoken.txt](https://github.com/yaronn/xml-crypto/files/1827391/testtoken.txt)
[Audkenni_Chain.txt](https://github.com/yaronn/xml-crypto/files/1827392/Audkenni_Chain.txt)

**Comment by einarjohnson** [comment]
I have also tried taking the _X509Certificate_ from the SAML2 token and using that as a FileKeyInfo into the keyinfoProvider. Same error happens, checkSignature fails.

**Comment by einarjohnson** [comment]
Also, if I use the XmlDSigJs library the signature from the exact same token is verified without any problems
```
    XmlDSigJs.Application.setEngine("OpenSSL", crypto);
    "use strict";
    let docSig = XmlDSigJs.Parse(samlxml);
    let signature = docSig.getElementsByTagNameNS("http://www.w3.org/2000/09/xmldsig#", "Signature");
    let signedXml = new XmlDSigJs.SignedXml(docSig);
    signedXml.LoadXml(signature[0]);
    signedXml.Verify()
        .then(res => {
            console.log("Íslykill signature OK:", res);       // Signature status: true
        })
        .catch(e =>  {
            throw new Error('Undirskrift ekki rétt');
        }
        );
```
Is this an indicator there is a problem/bug in the xml-crypto library?

**Comment by Hinaser** [comment]
Hi @einarjohnson 
I recently found out that xml-crypto has issues in processing 'non-exclusive c14n' such as:
http://www.w3.org/TR/2001/REC-xml-c14n-20010315

The above non-exclusive canonicalization(xml normalization) alters original xml before signing but xml-crypto needs more lines to handle it.

I will send a PR soon.

**Comment by einarjohnson** [comment]
that's brilliant news, would love to be able to use the xml-crypto lib to solve my problem instead of the XmlDSigJs hack I am resorting to now.

**Comment by Hinaser** [comment]
@einarjohnson You are lucky man! I just confirmed that your SAML restored from testtoken.xml can be verified successfully!
Please wait until I submit PR.

**Comment by Hinaser** [comment]
In case you want to try my PR before being merged, run the below command to install my one.
```
npm install --save https://github.com/Hinaser/xml-crypto.git#patch-for-non-exclusive-c14n
```

[xml-crypto-trying.zip](https://github.com/yaronn/xml-crypto/files/2085280/xml-crypto-trying.zip)

You can try demo by unzip the above file and execute command as below:
```
cd xml-crypto-trying
npm install
node main.js
```

You can look into `main.js` if you want to know what it does.
