### ISSUE TITLE
Avoid id in signature

### ISSUE THREAD

**Issue by giryco** [yaronn/xml-crypto#182]
Based in your main example:

`var SignedXml = require('xml-crypto').SignedXml	  
	  , fs = require('fs')

	var xml = "<library>" +
	            "<book>" +
	              "<name>Harry Potter</name>" +
	            "</book>" +
	          "</library>"

	var sig = new SignedXml()
	sig.addReference("//*[local-name(.)='book']")    
	sig.signingKey = fs.readFileSync("client.pem")
	sig.computeSignature(xml)
	fs.writeFileSync("signed.xml", sig.getSignedXml())`

How can I avoid Id="_0" to be added to book tag on signed xml?

**Comment by VaLThieL** [comment]
@giryco how you avoid the Id="_0" ?
