### ISSUE TITLE
Support for encryptio

### ISSUE THREAD

**Issue by Bytegardener** [yaronn/xml-crypto#194]
Hi there, 
Many thanks for the a great library. 
Just checking to see if support for encryption has been added?
I am currently signing xml documents using this package, and trying to use another one to encrypt, but am unable to do so.

**Comment by LoneRifle** [comment]
Hi @Bytegardener - this library is currently being passively maintained, so it is unlikely that we will add support for encryption. Hope this helps!

**Comment by Bytegardener** [comment]
Hi @LoneRifle  thanks for the prompt response. 
Do you/the team provide your services (at a fee) to other companies in this area (namely encryption/signing xml documents in node?)

**Comment by LoneRifle** [comment]
I'm afraid we don't! We're just volunteering our time to oversee PRs submitted against this repo. You may want to consider IssueHunt to find someone willing to take this on

**Comment by Bytegardener** [comment]
Thanks very much. I'll look into Issue Hunt.
