### ISSUE TITLE
Module pulls in test files

### ISSUE THREAD

**Issue by dosullivan557** [yaronn/xml-crypto#221]
I install your module in an application, it copies over .pem and .key files that are in your tests. This means that when we put our application through security scans, it fails because it finds these files and classifies them as sensitive data. What I'm asking is whether you can not include these in the bundled version of the application.

To resolve it, you can have a section in the package.json that doesn't pull the test files over to the build of the module when it is pulled in.

**Comment by LoneRifle** [comment]
Fixed by #220
