### ISSUE TITLE
how to change sign enocode

### ISSUE THREAD

**Issue by MB222222** [yaronn/xml-crypto#224]
I was going to sign Iso-8859-1 encoded xml file using xml-crypto.
but I have gotten an problem. Because when i sign a document, it changed encoding utf-8 and then sign.
Because crypto.create() default encoding is utf-8. I checked this package. and it always given a default encoding value.
Is there any solution for this problem? or do i need to hack package?

**Comment by MB222222** [comment]
Ansewer is very simple, will not use this package.

**Comment by marahe-app** [comment]
How did you solve this? How are you doing the signatures then? I need help please.

**Comment by cjbarth** [comment]
@IT222222 , we're more than welcome to take a PR to address this. @marahe-app , you're unlikely to get much community help if you only post to this thread, which is already closed.
