### ISSUE TITLE
Security issue in @xmldom/xmldom

### ISSUE THREAD

**Issue by andrewmcgivery** [yaronn/xml-crypto#260]
@xmldom/xmldom was just updated to version 0.8.3 to directly address a security issue.

![image](https://user-images.githubusercontent.com/4482878/195171908-eb17be36-700e-4f8f-9088-d9f93bb48100.png)

Can this library be updated? Looks like 0.8.* did have some breaking changes.

**Comment by jftanner** [comment]
Related dependabot PR: https://github.com/yaronn/xml-crypto/pull/261
