### ISSUE TITLE
How do I sign a root node?

### ISSUE THREAD

**Issue by biofractal** [yaronn/xml-crypto#38]
```
var SignedXml = require('xml-crypto').SignedXml   
      , fs = require('fs')
var xml = "<library><book><name>Harry Potter</name</book></library>"
var sig = new SignedXml()
sig.addReference("//*[local-name(.)='library']")    
sig.signingKey = fs.readFileSync("my-cert.pem")
sig.computeSignature(xml)
var signed = sig.getSignedXml()

var doc = new dom().parseFromString(signed)    
var signature = select(doc, "/*/*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0]
sig.keyInfoProvider = new FileKeyInfo("my-cert.pem")
sig.loadSignature(signature.toString())
var res = sig.checkSignature(xml)
if (!res) console.log(sig.validationErrors)
```
The following code above signs some sample xml and then validates the signature. It fails because the digests do not match. Presumably this is because I am attempting to sign the root node.

In your help file you say:

```
sig.getSignedXml() returns the original xml document with the signature pushed as the last child of
 the root node (as above). This assumes you are not signing the root node but only sub node(s) 
otherwise this is not valid. If you do sign the root node call sig.getSignatureXml() to get just the
 signature part and sig.getOriginalXmlWithIds() to get the original xml with Id attributes added on 
relevant elements (required for validation).
```

However I am afraid I don't understand what you mean by this. I would be very grateful if you could provide a code example of showing how to sign the root node of the test xml. 

In actual fact I am looking to generate an _enveloped_ signature. Is this possible with xml-crypto?

Thanks

**Comment by vitalii** [comment]
Hey, biofractal,  have you found the solution for your issue? I met the same problem. Can't sign authreq for third part validation. I saw dependants  of xml-crypto, but they signed urls instead of root node of xml. I would be grateful for any help.

**Comment by bjrmatos** [comment]
this should be more easy in the last version, please review the docs.

examples are coming..

since this is not a issue.. i'm closing it, feel free to comment if you have any problems
