### ISSUE TITLE
C14N canonicalization errors

### ISSUE THREAD

**Issue by KevinHorvatin** [yaronn/xml-crypto#40]
The C14N algorithm implementation leaves comments and removes data it shouldn't.

See my tests here: https://github.com/KevinHorvatin/xml-c14n-tests

I am working on patches, but if you already have some ideas. That would be appreciated.

Thanks

**Comment by yaronn** [comment]
Thanks @KevinHorvatin!

I was not aware of these issues and a patch will be welcomed. Possibly some of them originate from the xmldom dependency. currrently xml-crypto uses a fork of xmldom which is not on par with latest xmldom (b/c of some historical regression in xmldom). you might want to try to change the xmldom-fork-fixed dependency to xmldom and see if that helps.

**Comment by KevinHorvatin** [comment]
Pull request submitted for this issue:
https://github.com/yaronn/xml-crypto/pull/41

This will fix the comments issue but not the PI data issue.

**Comment by yaronn** [comment]
Thanks @KevinHorvatin , great work! I have pushed the new version to npm.
