### ISSUE TITLE
using v1.2 node got into issue when run  npm test

### ISSUE THREAD

**Issue by smartmouse** [yaronn/xml-crypto#44]
✖ Exclusive canonicalization works on complex xml
✖ Exclusive canonicalization removes Comments

✖ signer creates correct signature values

Assertion Message: wrong signature format

AssertionError: '<Body xmlns="http://schemas.xmlsoap.org/soap/envelope/">&#xD;

✖ Exclusive canonicalization sorts upper case attributes before lower case

AssertionError: '<x Id="" id=""></x>' == '<x id="" Id=""></x>'

✖ verify valid signature

Assertion Message: expected signature to be valid, but it was reported invalid

FAILURES: 9/128 assertions failed (672ms)
npm ERR! Test failed.  See above for more details.

**Comment by yaronn** [comment]
I have just installed node v0.12.0 on a new ubuntu 14.04 server and all tests passed:

    OK: 128 assertions (701ms)

I have used those installation instructions:

https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories

**Comment by bjrmatos** [comment]
all tests pass for me too in v0.12.7.. feel free to comment if you have any problems
