### ISSUE TITLE
Is there any plans to support inclusive canonicalization? 

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [yaronn/xml-crypto#50]
Is there any plans to support inclusive canonicalization? 

I mean such canonicalization, where 
`canAlgo!= ...xml-exc-c14n...`  but `canAlgo==...REC-xml-c14n-...`

**Comment by yaronn** [comment]
No current plans. xml-crypto has extensibility mechanism so this can be implemented from the outside too.

**Comment by BaurzhanSakhariev** [comment]
Ok, thanks. Looks like exclusive and inclusive canonicalization are the same in the case of processing **not subset but whole document**.
