### ISSUE TITLE
sign anf verify in browser

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [yaronn/xml-crypto#51]
Is there any tutorial to use xml-crypto for signing and verification without Node?

May I verify signed xml without xmldom?

As far as I know, I can clone to local folder and use browserify tool, am I right? I tried to do this, but console says something like *XmlSigned object is not defined.*

**Comment by yaronn** [comment]
Hi @BaurzhanSakhariev 

I don't think xml-crypto will work as is on browsers since the 'crypto' node libary is not available. But I think a few people migrated xml-crypto to work on a browser by changing signing functions to use  https://github.com/digitalbazaar/forge and then browserify.
