### ISSUE TITLE
Is documentation up to date?

### ISSUE THREAD

**Issue by bjrmatos** [yaronn/xml-crypto#52]
Hello, i just find in the source code that a EnvelopedSignature transform is supported, but nothing of this is mentioned in the docs, also there are other things that i think are out-dated too, would you accept a pull request covering this?

**Comment by yaronn** [comment]
Hi @bjrmatos . I wold love to see a PR with enhancements to the documentation!

**Comment by bjrmatos** [comment]
Cool! i'll work on that

**Comment by bjrmatos** [comment]
waiting for #58 to resolve

**Comment by bjrmatos** [comment]
closed by #58
