### ISSUE TITLE
Support for prefixed signature

### ISSUE THREAD

**Issue by bjrmatos** [yaronn/xml-crypto#54]
Hello @yaronn, as discussed here #26 i'm starting to work in a pull request that support generate a prefixed signature. i've cloned the repo and after run `npm test` i see a failing test, do you have the same result?

![image](https://cloud.githubusercontent.com/assets/4262050/7736131/7643244e-ff07-11e4-99dc-5fc692b80d98.png)

**Comment by bjrmatos** [comment]
I just sent the PR here #56, let me know if something is wrong

**Comment by bjrmatos** [comment]
I have node 0.10.36 and windows 7

**Comment by yaronn** [comment]
do you still get the unit test error? I don't get it on windows 7 / node 0.10.28 or Ubuntu 12 / node 0.10.33.

**Comment by bjrmatos** [comment]
Yes, i still getting error on 0.10.36 / 0.10.28 - windows7 (x86).. looks that this is something weird :S

**Comment by yaronn** [comment]
can you print sig.validationErrors in the end of saml-response-test.js (13) to see what is the validaiton issue? might be related to whitepsace handling in the OS.

**Comment by bjrmatos** [comment]
i've found that is a problem of line endings..

this is what i get from `sig.validationErrors` -> `ERRORS:
[ 'invalid signature: for uri #pfx94e4a319-b6f7-4a40-25d1-01fcb642e4c5 calculated digest is 4gQRC7VRHftCaH+mTcIVkUFHpxY= but the xml to validate supplies digest fc21hh1bKZpaMNjx9HfOfVelfWw=' ]`

when i clone the repository from git, git converts line endings to windows style (CRLF)

My git config ->
![image](https://cloud.githubusercontent.com/assets/4262050/7786431/6dea2762-0195-11e5-99e9-5948a50a9fbf.png)

however.. if i download the repository from github as a zip and run the tests, everything is ok.

is this the correct behaviour? does the xml canonicalization spec defines something to normalize line endings across OS? or is it more related to the digest calculation?

**Comment by yaronn** [comment]
good catch!

digest calculation basically takes the xml (with white spaces if any) and calculates its hash as a stream of data. so changing the whitespace format will break the digest calculation. this is the desired behavior.

**Comment by bjrmatos** [comment]
thnks, i'll work on #55, stay tuned :)

**Comment by yaronn** [comment]
looking forward to it!
