### ISSUE TITLE
Is there a way to implement Xades BES?

### ISSUE THREAD

**Issue by galcivar** [yaronn/xml-crypto#61]
We need to encrypt XML files with:
http://oficinavirtual.mityc.es/componentes/mityclibxades/integrator-guide/xades-bes-sign.html

Is there a way to implement it?

**Comment by yaronn** [comment]
I think you need to sign and not encrypt (anyway xml-crypto can only sign).
xml-crypto has not special support to the canonicalization algorithm in the sample (http://www.w3.org/TR/2001/REC-xml-c14n-20010315) but maybe things will work as is if the server is willing to accept different algorithm. I suggest you try to first signing sample in the README and just replace the xml and xpath with your xml.

**Comment by bjrmatos** [comment]
i'm closing this until more information is provided.

**Comment by rmhrisk** [comment]
This is what they want : https://xadesnet.codeplex.com/

I would like the same thing ;)

**Comment by bjrmatos** [comment]
i've opened a separate issue for XAdES :+1:
