### ISSUE TITLE
Support http://www.w3.org/TR/2001/REC-xml-c14n-20010315 canonicalization

### ISSUE THREAD

**Issue by dominykas** [yaronn/xml-crypto#68]
I have no idea how it differs from all the other c14n - will research myself and PR if I can figure it out...

**Comment by bjrmatos** [comment]
let me know if you can figure it out

i will investigate later (probably the next week)

**Comment by dominykas** [comment]
There's a bit of a curve there, alright. Probably would take a lot faster to implement this for someone familiar with the problem already, especially considering that "Exclusive XML Canonicalization are the same as for Canonical XML [XML-C14N] with the following exceptions" http://www.w3.org/TR/xml-exc-c14n/#sec-Specification

I do like the method signature in PHP though: http://php.net/manual/en/domnode.c14n.php - it seems to support everything (except the enveloped one?). Digging deeper, I found that it all boils down to `libxml`'s implementation: https://git.gnome.org/browse/libxml2/tree/c14n.c

At the very least it should be possible to copy their test cases: https://git.gnome.org/browse/libxml2/tree/test/c14n :)

I think it would also be a good idea to bring https://www.npmjs.com/package/xml-c14n up to date (with tests and all) and use that here (it is reusable code, at the end of the day). @deoxxa, ping?

**Comment by Sk1Zy** [comment]
Any news on this? @bjrmatos

**Comment by klinkov** [comment]
Any news? Still not working :(

**Comment by bjrmatos** [comment]
sorry guys, right now i don't have the time to implement this but i'm planning to do it some time later.. PR are highly welcome!

**Comment by yaronn** [comment]
:+1:

**Comment by diegoavidal** [comment]
please i really need this :+1:

**Comment by rmhrisk** [comment]
We have built on this excellent library have a package that implements C14N here: https://www.npmjs.com/package/xadesjs

**Comment by bjrmatos** [comment]
@rmhrisk congrats for the release!

**Comment by LoneRifle** [comment]
Fixed in #116
