### ISSUE TITLE
enveloped transformation + exclusive-canonicalization

### ISSUE THREAD

**Issue by siacomuzzi** [yaronn/xml-crypto#72]
Can both algorithms work together? I'm getting a [digest mismatch error](https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L315) with the following "transforms" element:

```
<ds:Transforms>
  <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
  <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
    <xc14n:InclusiveNamespaces xmlns:xc14n="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs saml xsi"/>
  </ds:Transform>
 </ds:Transforms>
```

Thanks

**Comment by siacomuzzi** [comment]
I'll try with this -> https://github.com/yaronn/xml-crypto/issues/48

**Comment by siacomuzzi** [comment]
I fixed that with your workaround, thanks @yaronn !

But I'm wondering if these namespaces should be added in the SAML assertion element by my SAML Identity Provider or it should be handled from my side (xml-crypto code in this case).

**Comment by siacomuzzi** [comment]
the following works for me:

```
if (ref.inclusiveNamespacesPrefixList) {
  var prefixList = ref.inclusiveNamespacesPrefixList instanceof Array ? ref.inclusiveNamespacesPrefixList : ref.inclusiveNamespacesPrefixList.split(' ');
  var supported_definitions = {
    'xs': 'http://www.w3.org/2001/XMLSchema',
    'xsi': 'http://www.w3.org/2001/XMLSchema-instance',
    'saml': 'urn:oasis:names:tc:SAML:2.0:assertion'
  }

  prefixList.forEach(function (prefix) {
    elem[0].setAttributeNS('http://www.w3.org/2000/xmlns/', 'xmlns:' + prefix, supported_definitions[prefix]);
  });
}
```

**Comment by yaronn** [comment]
great this works out and thanks for sharing the solution!

**Comment by bjrmatos** [comment]
@yaronn is this something that we can put in core? what needs to be done to make it ready? i have no idea which is the behaviour of InclusiveNamespaces transform :smiley:

**Comment by bjrmatos** [comment]
related to #60

**Comment by siacomuzzi** [comment]
I don't know why yet, but the following is not working with my workaround:

```
<ds:Transforms>
  <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
  <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
    <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="xs"/>
  </ds:Transform>
</ds:Transforms>
```

I'm getting the digest mismatch error again.
