### ISSUE TITLE
'invalid signature : Signature generation not working properly

### ISSUE THREAD

**Issue by iamnewspecies** [yaronn/xml-crypto#93]
I am using the following code as given in the readme. But I am getting "invalid signature" when I verify the code with the code given on Readme of project. What am I doing wrong?

I know that the verifier is generating the correct digestValue but the initial code which generates the hash is generating the correct digestValue.

```
var SignedXml = require('xml-crypto').SignedXml   
      , fs = require('fs')

    var sig = new SignedXml();
    sig.addReference("//*[local-name(.)='HbtMsg']", ['http://www.w3.org/2000/09/xmldsig#enveloped-signature'], 'http://www.w3.org/2001/04/xmlenc#sha256');
    sig.signingKey = fs.readFileSync("./keys/pri.pem");
    sig.canonicalizationAlgorithm = 'http://www.w3.org/2001/10/xml-exc-c14n#';
    sig.signatureAlgorithm = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
    sig.computeSignature(xml);
    fs.writeFileSync("./tests/signed.xml", sig.getSignedXml());

 var select = require('xml-crypto').xpath
      , dom = require('xmldom').DOMParser
      , SignedXml = require('xml-crypto').SignedXml
      , FileKeyInfo = require('xml-crypto').FileKeyInfo  
      , fs = require('fs')

    var xml = fs.readFileSync("./tests/signed.xml").toString()
    var doc = new dom().parseFromString(xml)    

    var signature = select(doc, "/*/*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0]
    var sig = new SignedXml()
    sig.keyInfoProvider = new FileKeyInfo("./keys/pub.pem")
    sig.loadSignature(signature.toString())
    var res = sig.checkSignature(xml)
    if (!res) console.log(sig.validationErrors)
```

I am getting this as the response : 

`[ 'invalid signature: for uri #_0 calculated digest is I6QnT6OKRlqeJXVGIb/UIiV1k/ArtW5/fAJkjGoxP8Y= but the xml to validate supplies digest 3g7fAmI5/vWlkDLK4zlU3/GSmjdFOlOCGs+pNMNqSVM=' ]`

**Comment by iamnewspecies** [comment]
After doing console log of :

```
SignedXml.prototype.createReferences = function(doc, prefix) {

  var res = ""

  prefix = prefix || ''
  prefix = prefix ? prefix + ':' : prefix

  for (var n in this.references) {
    if (!this.references.hasOwnProperty(n)) continue;

    var ref = this.references[n]
      , nodes = select(doc, ref.xpath)

    if (nodes.length==0) {
      throw new Error('the following xpath cannot be signed because it was not found: ' + ref.xpath)
    }

    for (var h in nodes) {
      if (!nodes.hasOwnProperty(h)) continue;

      var node = nodes[h]
      if (ref.isEmptyUri) {
        res += "<" + prefix + "Reference URI=\"\">"
      }
      else {
        var id = this.ensureHasId(node);
        ref.uri = id
        res += "<" + prefix + "Reference URI=\"#" + id + "\">"
      }
      res += "<" + prefix + "Transforms>"
      for (var t in ref.transforms) {
        if (!ref.transforms.hasOwnProperty(t)) continue;

        var trans = ref.transforms[t]
        var transform = this.findCanonicalizationAlgorithm(trans)
        res += "<" + prefix + "Transform Algorithm=\"" + transform.getAlgorithmName() + "\" />"
      }

      var canonXml = this.getCanonXml(ref.transforms, node)
      console.log(canonXml);
      var digestAlgorithm = this.findHashAlgorithm(ref.digestAlgorithm)
      res += "</" + prefix + "Transforms>"+
             "<" + prefix + "DigestMethod Algorithm=\"" + digestAlgorithm.getAlgorithmName() + "\" />"+
              "<" + prefix + "DigestValue>" + digestAlgorithm.getHash(canonXml) + "</" + prefix + "DigestValue>"+
              "</" + prefix + "Reference>"
    }
  }

  return res
}
```

and console.log of this : 
```

SignedXml.prototype.validateReferences = function(doc) {
  for (var r in this.references) {
    if (!this.references.hasOwnProperty(r)) continue;

    var ref = this.references[r]

    var uri = ref.uri[0]=="#" ? ref.uri.substring(1) : ref.uri
    var elem = [];

    if (uri=="") {
      elem = select(doc, "//*")
    }
    else {
      for (var index in this.idAttributes) {
        if (!this.idAttributes.hasOwnProperty(index)) continue;

        elem = select(doc, "//*[@*[local-name(.)='" + this.idAttributes[index] + "']='" + uri + "']")
        if (elem.length > 0) break;
      }
    }

    if (elem.length==0) {
      this.validationErrors.push("invalid signature: the signature refernces an element with uri "+
                        ref.uri + " but could not find such element in the xml")
      return false
    }
    var canonXml = this.getCanonXml(ref.transforms, elem[0], { inclusiveNamespacesPrefixList: ref.inclusiveNamespacesPrefixList });
    console.log(canonXml);
    var hash = this.findHashAlgorithm(ref.digestAlgorithm)
    var digest = hash.getHash(canonXml)

    if (digest!=ref.digestValue) {
      this.validationErrors.push("invalid signature: for uri " + ref.uri +
                                " calculated digest is "  + digest +
                                " but the xml to validate supplies digest " + ref.digestValue)

      return false
    }
  }
  return true
}
```

I get different values in the canonXml.

One has : 
<HbtMsg type="ALIVE" value="NA" Id="_0"/>
And the other has : 
<HbtMsg Id="_0" type="ALIVE" value="NA"></HbtMsg>

These two are basically the same.** How should I handle this issue?**
Note : The second canonXml yields the correct hash.

**Comment by bjrmatos** [comment]
can you give us the original xml that you are trying to sign?

**Comment by bjrmatos** [comment]
i was able to reproduce your issue, to make it work you only need to add `http://www.w3.org/2001/10/xml-exc-c14n#` to the array of transforms.

demo:
![xml-crypto-issue](https://cloud.githubusercontent.com/assets/4262050/13382972/ef616544-de4e-11e5-8097-46a9e3c334ea.gif)

**Comment by bjrmatos** [comment]
the reason for it doesn't work without specifying the exc-14n transform is because [this line](https://github.com/yaronn/xml-crypto/blob/master/lib/signed-xml.js#L417).

As you can see when xml-crypto tries to load a reference (necessary to validate the whole signature), if it detects that the reference has only used the `http://www.w3.org/2000/09/xmldsig#enveloped-signature` transform, it adds a `http://www.w3.org/2001/10/xml-exc-c14n#` transform just to support windows mobile store signatures (as the comment says), i don't know if that is the correct behaviour, i don't think it is the correct behaviour. but @yaronn knows more about that case than me. 

i would prefer to add an option `implicitEXC14N` to handle cases like the windows mobile store signatures

**Comment by bjrmatos** [comment]
just for the record.. i knew about this special case sometime ago (I found it in one of the applications developed) but didn't say nothing because i was able to find a workaround :sweat_smile:

**Comment by iamnewspecies** [comment]
There is one more problem now. I referred to this [URL](https://github.com/yaronn/xml-crypto/issues/24) to fix empty reference thing. I have same console.log in place as I mentioned in my second comment. Now the output I get for those console.log is: 
1st

`<HbtMsg type="ALIVE" value="NA"></HbtMsg>`

2nd

`<upi:ReqHbt xmlns:upi="http://npci.org/upi/schema/"><Head msgId="HENSVVR4QZS7X1UGPY7JGZZ444PL9T2C" orgId="410004" ts="2015-02-16T22:02:25+05:30" ver="1.0"></Head><Txn id="2241" note="Heart beat" ref="" ts="2015-02-16T22:02:25+05:30" type="Hbt"></Txn><HbtMsg type="ALIVE" value="NA"></HbtMsg></upi:ReqHbt>`

This is causing the same error I got above. What am I doing wrong?

**Comment by bjrmatos** [comment]
in order to help you, this time i will need the original xml so i can test it on my own

**Comment by iamnewspecies** [comment]
I had already provided my original XML in the previous comment. 
Still here is my input : 
`<?xml version="1.0" encoding="UTF-8" standalone="no"?><upi:ReqHbt xmlns:upi="http://npci.org/upi/schema/"><Head msgId="HENSVVR4QZS7X1UGPY7JGZZ444PL9T2C" orgId="410004" ts="2015-02-16T22:02:25+05:30" ver="1.0"/><Txn id="2241" note="Heart beat" ref="" ts="2015-02-16T22:02:25+05:30" type="Hbt"/><HbtMsg type="ALIVE" value="NA"/></upi:ReqHbt>`

**Comment by bjrmatos** [comment]
ups! sorry didn't see it, i have to go out will review it tomorrow

**Comment by iamnewspecies** [comment]
@yaronn

**Comment by bjrmatos** [comment]
ok, as the xml signature process describes if you specify an empty URI for the reference, that means that the whole xml document is signed not just the `HbtMsg` tag, thats the reason why your second console.log is `<upi:ReqHbt xmlns:upi="http://npci.org/upi/schema/"><Head msgId="HENSVVR4QZS7X1UGPY7JGZZ444PL9T2C" orgId="410004" ts="2015-02-16T22:02:25+05:30" ver="1.0"></Head><Txn id="2241" note="Heart beat" ref="" ts="2015-02-16T22:02:25+05:30" type="Hbt"></Txn><HbtMsg type="ALIVE" value="NA"></HbtMsg></upi:ReqHbt>`

**Comment by bjrmatos** [comment]
if you need to sign the whole document and put the signature inside the `HbtMsg` tag you can use the `location` option in the `computeSignature` method. 

[example](https://github.com/yaronn/xml-crypto#how-to-specify-the-location-of-the-signature)

**Comment by iamnewspecies** [comment]
Thanks a lot. 

Had to change the 
`sig.addReference("//*[local-name(.)='HbtMsg']", ['http://www.w3.org/2000/09/xmldsig#enveloped-signature'], 'http://www.w3.org/2001/04/xmlenc#sha256');`

to 

`sig.addReference("//*[local-name(.)='ReqHbt']", ['http://www.w3.org/2000/09/xmldsig#enveloped-signature'], 'http://www.w3.org/2001/04/xmlenc#sha256');`
