### ISSUE TITLE
xpath bug in Verifying Xml documents example 

### ISSUE THREAD

**Issue by christian-boks** [yaronn/xml-crypto#97]
The example says:
`var signature = select(doc, "/*/*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0]`

But it should be:
`var signature = select(doc, "//*[local-name(.)='Signature' and namespace-uri(.)='http://www.w3.org/2000/09/xmldsig#']")[0]`

**Comment by bjrmatos** [comment]
in fact the xpath is correct, it will look in the second level of hierarchy of the XML (where the signature is located in the example)

**Comment by christian-boks** [comment]
The sample works just fine when you use `//*` All the other examples use this notation, and if you use a real bit of XML like a SAMLv2.0 Response it will work too, whereas `/*/*` will not.

**Comment by bjrmatos** [comment]
> and if you use a real bit of XML like a SAMLv2.0 Response it will work too, whereas /*/* will not.

the xpath will always depend on the format of the xml.

if you can send a PR updating the example i have no problem to merge it :smile:
